apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sensoragents.digitaltwin.example.com
spec:
  group: digitaltwin.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sensorType:
                  type: string
                protocol:
                  type: string
                image:
                  type: string
                sensorId:
                  type: string
                sensorLocationId:
                  type: string
                sitewiseAssetId:
                  type: string
                sitewisePropertyId:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: sensoragents
    singular: sensoragent
    kind: SensorAgent
    shortNames:
      - sa
