apiVersion: v1
kind: Namespace
metadata:
  name: cicd

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: cicd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          env:
            - name: JENKINS_ADMIN_ID
              value: "admin"
            - name: JENKINS_ADMIN_PASSWORD
              value: "your-jenkins-password"
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: cicd
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
